import math

# --- Global Configuration ---
TOTE_MAX_LENGTH = 850
TOTE_MAX_WIDTH = 650
TOTE_MAX_HEIGHT = 400
TOTE_MAX_VOLUME = TOTE_MAX_LENGTH * TOTE_MAX_WIDTH * TOTE_MAX_HEIGHT
HEIGHT_MAP_RESOLUTION = 10 # mm

GRID_DIM_X = math.ceil(TOTE_MAX_LENGTH / HEIGHT_MAP_RESOLUTION)
GRID_DIM_Y = math.ceil(TOTE_MAX_WIDTH / HEIGHT_MAP_RESOLUTION)
